version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - /data/mysql
  spring-boot-tax-app:
    image: spring-boot-tax-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app