# Use root/example as user/password credentials
version: '3.1'

services:

  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tax_calculator
    restart: always
    ports:
      - "3306:3306"

  app:
    image: spring-boot-tax-calculator
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8080:8080"
    links:
      - mysql-docker-container:mysql
